project_name: feelthemovies
builds:
- goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  main: ./cmd/feelthemovies/main.go
  env:
  - CGO_ENABLED=0
  ldflags:
  -s -w -extldflags "-static" -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}"
  