project_name: feelthemovies
builds:
- goos:
  - linux
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -extldflags "-static" -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}"

release:
  name_template: "v{{.Version}}"

archive:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

sign:
  artifacts: checksum