project_name: feelthemovies

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  env:
    - CGO_ENABLED=0
  main: ./cmd/feelthemovies/main.go
  ldflags:
    - -s -w -X main.build={{.Version}}
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64

release:
  name_template: "v{{.Version}}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

archives:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
