# Language
language: go

# Enable sudo
# sudo: false

# Golang versions
go:
  - master

# The API needs MySQL
services:
  - mysql

# MySQL config
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

# Build only the latest commit
git:
  depth: 1

# MySQL / Overalls config
before_install:
  - mysql -e 'create database api_feelthemovies;'
  - mysql api_feelthemovies < $GOPATH/src/github.com/cyruzin/feelthemovies/db/api_feelthemovies.sql
  - go get go-sql-driver/mysql get github.com/joho/godotenv github.com/gorilla/mux go-playground/validator rs/cors github.com/mattn/goveralls

# Overalls / Test scripts 
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./...

# Do not notify
notifications:
  email: false