sudo: false

dist: xenial

language: go

go:
  - 1.11.x

services:
 - mysql

git:
  depth: 1

before_script:
  - mysql -u root -e 'CREATE DATABASE api_feethemovies;'
  - mysql -u root api_feethemovies < db/api_feelthemovies.sql
  - sleep 25
  - go get -t -v ./...  
  - go get github.com/mattn/goveralls  
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./... -race

notifications:
  email: false