dist: xenial 

language: go

go:
- 1.12.x

services:
- docker

git:
  depth: 1

before_install:
  - go get github.com/mattn/goveralls

script:
  - go get -v -t -d ./... 
  - $GOPATH/bin/goveralls -service=travis-ci

deploy:
- provider: script
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false