# Language
language: go

# Golang versions
go:
  - 1.11.x

services:
 - docker

#env:
#- DOCKER_COMPOSE_VERSION=1.23.2

# Build only the latest commit
git:
  depth: 1

# Docker / Overalls config
before_install:
  - sudo service mysql stop
  - docker-compose up -d
  - docker ps -a
  - go get -t -v ./...  
  - go get github.com/mattn/goveralls 

# Overalls / Test script 
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - docker exec -ti api-mysql bash
  - mysql
  - use api_feelthemovies;
  - select * from genres;
  - quit;
  - exit
  - go test -v ./...

# Do not notify
notifications:
  email: false