# Sudo option
sudo: false

# SO
dist: xenial

# Language
language: go

# Golang versions
go:
  - 1.11.x

services:
 - docker

addons:
  apt:
    packages:
      - docker-ce

# Build only the latest commit
git:
  depth: 1

# Docker / Overalls config
before_install:
  - docker-compose up -d
  - go get -t -v ./...  
  - go get github.com/mattn/goveralls 

# Overalls / Test scripts
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./...

# Do not notify
notifications:
  email: false