language: go

go:
  - 1.11.4

services:
  - mysql

git:
  depth: 1

before_install:
  - mysql < db/api_feelthemovies.sql

script:
  - go get -v -t -d ./... 
  - go get github.com/mattn/goveralls  
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./... -race

notifications:
  email: false