language: go

go:
  - 1.11.x

dist: xenial

services:
 - docker

git:
  depth: 1

before_script:
  - docker-compose up -d
  - docker-compose exec -d mysql /.entrypoint.sh
  - sleep 10
  - go get -t -v ./...  
  - go get github.com/mattn/goveralls  
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./... -race

notifications:
  email: false