sudo: required

language: go

go:
  - 1.11.x

dist: trusty

services:
 - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

git:
  depth: 1

before_script:
  - mysql -u root -e 'CREATE DATABASE api_feelthemovies;'
  - mysql -u root api_feelthemovies < db/api_feelthemovies.sql
  - go get -t -v ./...  
  - go get github.com/mattn/goveralls  
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./... -race

notifications:
  email: false