# Language
language: go

# Enable sudo
sudo: false

# Enabling Go Modules 
# This won't be necessary in version 1.12
env:
  - GO111MODULE=on

# Golang versions
go:
  - 1.11.x

# The API needs MySQL
services:
  - mysql

# MySQL config
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

# Build only the latest commit
git:
  depth: 1

# MySQL / Overalls config
before_install:
  - mysql -e 'create database api_feelthemovies;'
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql_upgrade -u root -pnew_password
  - service mysql restart
  - mysql api_feelthemovies < db/api_feelthemovies.sql
  - go get -t -v ./...  
  - go get github.com/mattn/goveralls

# Overalls / Test scripts 
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v -race ./...

# Do not notify
notifications:
  email: false