# Language
language: go

dist: xenial

# Golang versions
go:
  - 1.11.x

services:
 - docker

# Build only the latest commit
git:
  depth: 1

# Docker / Overalls config
before_install:
  - sudo apt get update && sudo apt get upgrade
  - docker-compose up -d
  - docker ps
  - go get -t -v ./...  
  - go get github.com/mattn/goveralls 

# Overalls / Test scripts
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./...

# Do not notify
notifications:
  email: false