version: 1.1.{build}
image: Previous Ubuntu1604
clone_depth: 1
clone_folder: gopath/src/github.com/cyruzin/feelthemovies
services:
- docker
environment:
  DBUSER:
    secure: D96kLX50Wgb9dLMp9fTDrw==
  DBPASS:
    secure: 3uPmkr+oh1vXGrjippcSeA==
  DBHOST:
    secure: /PCUeNHuS71rh4GYzoRc0Q==
  REDISADDR:
    secure: 14sChUaD8DQwH6ClqLTgeA==
  REDISPASS:
    secure: F107pnl4jI09Elw95j8V7A==
  JWTSecret:
    secure: 7+ydAw/1wIDUVAc01SluVw==
  NEWRELICKEY:
    secure: H7zzbZZm/V21rW/JgZeDo/9fFwihvyk6C4slqSJkYH1WfmQYxyjalx3T9rbjoB+v
build:
  verbosity: minimal
test_script:
- cmd: "docker-compose up -d \ngo version\n    go get -v -t -d ./...\n    if [ -f Gopkg.toml ]; then\n        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh\n        dep ensure\n    fi\n    go test -v ./... -race"
test: off
deploy: off