version: "3.3"

services: 

  mysql:
    image: mysql:5.7
    container_name: api-mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports: 
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Password12!
  
  redis:
    image: redis:5.0.3-alpine
    container_name: api-redis
    command: redis-server --requirepass 69Wm3ZA2ianh8uUX
    ports: 
      - 6379:6379