version: "3.3"

services: 

  mysql:
    image: maria-db:10.3
    container_name: api-mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true