version: "3.1"

services: 

  mysql:
    image: mysql:8.0.13
    container_name: api-mysql
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=api_feelthemovies