version: "3.7"

services: 

  mysql:
    image: mysql:5.7
    container_name: api-mysql
    volumes:
    - ./db/api_feelthemovies.sql:/docker-entrypoint-initdb.d/api_feelthemoviesl.sql
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=api_feelthemovies