version: "3.3"

services: 

  mysql:
    image: mariadb:10.0.37-xenial
    container_name: api-mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true