version: "3.3"

services: 

  mysql:
    image: mysql:5.7
    container_name: api-mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports: 
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Password12!