version: "3.3"

services: 

  mysql:
    image: mysql:5.7
    container_name: api-mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      #- MYSQL_DATABASE=api_feelthemovies