version: "3.1"

services: 

  mysql:
    image: mariadb:10.3
    container_name: api-mysql
    volumes:
    - ./db/api_feelthemovies.sql:/docker-entrypoint-initdb.d/api_feelthemoviesl.sql
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=api_feelthemovies
    command: >
      bash -c "docker exec -ti api-mysql bash && mysql && use api_feelthemovies; && select * from genres; && quit; && exit"