version: "3.1"

services: 

  mysql:
    image: mysql:5.7
    container_name: api-mysql
    command: bash -c "mysql -e 'select * from genres' api_feelthemovies;"
    volumes:
    - ./db/api_feelthemovies.sql:/docker-entrypoint-initdb.d/api_feelthemoviesl.sql
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=api_feelthemovies